title: Denis Korchagin
email: denis.korchagin.1995@gmail.com
description: >-
  A personal blog on software development, with occasional insights into psychology and workplace dynamics.
url: "https://denis-korchagin95.github.io/"
baseurl: "/devblog"
github_username: denis-korchagin95
linkedin_username: denis-korchagin

theme: minima
plugins:
  - jekyll-feed

minima:
  skin: classic
